server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:my-database.cn450lx5jvca.ap-south-1.rds.amazonaws.com}:3306/productdb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can set this to "create" for development, but "update" or "none" for production
      database-platform: org.hibernate.dialect.MySql57InnoDBDialect
  application:
    name: PRODUCT-SERVICE
  config:
   import: configserver:http://3.109.144.20:9296

          
#  eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}




